import './globals.css'
import { Inter } from 'next/font/google'
import { ThemeProvider } from "@material-tailwind/react";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Good Charme | Combo Hoàn Tiền',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
        <div className='px-10 py-10'>{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
